modules:

manual-clients:
  - api-shortname: bigquery
    distribution-name: cloud.google.com/go/bigquery
    description: BigQuery
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/bigquery/latest
    release-level: stable
    library-type: GAPIC_MANUAL
  - api-shortname: bigtable
    distribution-name: cloud.google.com/go/bigtable
    description: Cloud BigTable
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/bigtable/latest
    release-level: stable
    library-type: GAPIC_MANUAL
  - api-shortname: compute-metadata
    distribution-name: cloud.google.com/go/compute/metadata
    description: Service Metadata API
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/compute/latest/metadata
    release-level: stable
    library-type: CORE
  - api-shortname: datastore
    distribution-name: cloud.google.com/go/datastore
    description: Cloud Datastore
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/datastore/latest
    release-level: stable
    library-type: GAPIC_MANUAL
  - api-shortname: clouderrorreporting
    distribution-name: cloud.google.com/go/errorreporting
    description: Cloud Error Reporting API
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/errorreporting/latest
    release-level: preview
    library-type: GAPIC_MANUAL
  - api-shortname: firestore
    distribution-name: cloud.google.com/go/firestore
    description: Cloud Firestore API
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/firestore/latest
    release-level: stable
    library-type: GAPIC_MANUAL
  - api-shortname: firestore-metadata
    distribution-name: cloud.google.com/go/functions/metadata
    description: Cloud Functions
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/functions/latest/metadata
    release-level: preview
    library-type: CORE
  - api-shortname: iam
    distribution-name: cloud.google.com/go/iam
    description: Cloud IAM
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/iam/latest
    release-level: stable
    library-type: CORE
  - api-shortname: logging
    distribution-name: cloud.google.com/go/logging
    description: Cloud Logging API
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/logging/latest
    release-level: stable
    library-type: GAPIC_MANUAL
  - api-shortname: cloudprofiler
    distribution-name: cloud.google.com/go/profiler
    description: Cloud Profiler
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/profiler/latest
    release-level: stable
    library-type: AGENT
  - api-shortname: pubsub
    distribution-name: cloud.google.com/go/pubsub
    description: Cloud PubSub
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/pubsub/latest
    release-level: stable
    library-type: GAPIC_MANUAL
  - api-shortname: pubsublite
    distribution-name: cloud.google.com/go/pubsublite
    description: Cloud PubSub Lite
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/pubsublite/latest
    release-level: stable
    library-type: GAPIC_MANUAL
  - api-shortname: rpcreplay
    distribution-name: cloud.google.com/go/rpcreplay
    description: RPC Replay
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/latest/rpcreplay
    release-level: stable
    library-type: OTHER
  - api-shortname: spanner
    distribution-name: cloud.google.com/go/spanner
    description: Cloud Spanner
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/spanner/latest
    release-level: stable
    library-type: GAPIC_MANUAL
  - api-shortname: storage
    distribution-name: cloud.google.com/go/storage
    description: Cloud Storage (GCS)
    language: go
    client-library-type: manual
    client-documentation: https://cloud.google.com/go/docs/reference/cloud.google.com/go/storage/latest
    release-level: stable
    library-type: GAPIC_MANUAL

service-configs:

skip-module-scan-paths:
  # ignore the root module
  - .
  # Librarian released modules
  - bigquery
  - bigquery/v2
  - profiler
  - vertexai
  - spanner
  - datastore
  - firestore
  - containeranalysis
  - geminidataanalytics
  - locationfinder
  - configdelivery
  - serviceusage
  - servicemanagement
  - servicecontrol
  - orgpolicy
  - kms
  - grafeas
  - dataqna
  - certificatemanager
  - accessapproval
  - aiplatform
  - vmmigration
  - run
  - monitoring
  - iam
  - dialogflow
  - datastream
  - datacatalog
  - cloudbuild
  - workstations
  - workflows
  - websecurityscanner
  - webrisk
  - vpcaccess
  - vmwareengine
  - visionai
  - vision
  - videointelligence
  - video
  - translate
  - trace
  - tpu
  - texttospeech
  - telcoautomation
  - talent
  - support
  - streetview
  - storagetransfer
  - storageinsights
  - storagebatchoperations
  - speech
  - shopping
  - shell
  - servicehealth
  - servicedirectory
  - securityposture
  - securitycentermanagement
  - securitycenter
  - security
  - securesourcemanager
  - secretmanager
  - scheduler
  - retail
  - resourcemanager
  - redis
  - recommender
  - recommendationengine
  - recaptchaenterprise
  - rapidmigrationassessment
  - privilegedaccessmanager
  - privatecatalog
  - policytroubleshooter
  - policysimulator
  - phishingprotection
  - parametermanager
  - parallelstore
  - oslogin
  - osconfig
  - orchestration
  - oracledatabase
  - optimization
  - notebooks
  - networkservices
  - networksecurity
  - networkmanagement
  - networkconnectivity
  - netapp
  - modelarmor
  - migrationcenter
  - metastore
  - memorystore
  - memcache
  - mediatranslation
  - managedkafka
  - managedidentities
  - maintenance
  - lustre
  - lifesciences
  - language
  - iot
  - ids
  - identitytoolkit
  - iap
  - gsuiteaddons
  - gkemulticloud
  - gkehub
  - gkeconnect
  - gkebackup
  - functions
  - financialservices
  - filestore
  - essentialcontacts
  - edgenetwork
  - edgecontainer
  - documentai
  - cloudprofiler
  - pubsublite
  - domains
  - discoveryengine
  - devicestreaming
  - developerconnect
  - deploy
  - dataplex
  - datalabeling
  - datafusion
  - dataform
  - dataflow
  - container
  - contactcenterinsights
  - config
  - commerce
  - artifactregistry
  - analytics
  - ai
  - accesscontextmanager
  - advisorynotifications
  - compute/metadata
  - confidentialcomputing
  - cloudtasks
  - cloudquotas
  - clouddms
  - cloudcontrolspartner
  - chronicle
  - chat
  - channel
  - capacityplanner
  - binaryauthorization
  - billing
  - beyondcorp
  - batch
  - baremetalsolution
  - backupdr
  - automl
  - assuredworkloads
  - asset
  - area120
  - apps
  - maps
  - eventarc
  - apphub
  - appengine
  - apikeys
  - apigeeregistry
  - auth
  - auth/oauth2adapt
  - apihub
  - apigeeconnect
  - apigateway
  - alloydb
  - dataproc
  - dlp
  - longrunning
  - pubsub/v2
  - pubsub
  # unreleased modules
  - spanner/test/opentelemetry/test
