# Configure the behavior of the gemini code assist bot.
# More info:
# https://developers.google.com/gemini-code-assist/docs/customize-gemini-behavior-github
have_fun: false
memory_config:
  disabled: false
code_review:
  pull_request_opened:
    help: false
    # summary info is low value
    summary: false
    code_review: true
    include_drafts: true
