# Hand-maintained configuration for libraries.

global_files_allowlist:
 # Paths (currently just one) that need to modified during configure
 - path: "internal/generated/snippets/go.mod"
   permissions: "read-write"
