# Hand-maintained configuration for libraries.

global_files_allowlist:
 # Paths (currently just one) that need to modified during configure
 - path: "internal/generated/snippets/go.mod"
   permissions: "read-write"
 # Allow CHANGES.md to be rewritten. This is only used for the root module.
 # We don't want to add a source path of "." to the state file,
 # as that would include everything that's *not* in the module
 # as well. The root module includes a source path of "internal"
 # despite several subdirectories being tools which don't need
 # to be released as such; those are listed as released exclusion
 # paths in state.yaml.
 - path: "CHANGES.md"
   permissions: "read-write"

# All libraries with handwritten code (core, hybrid and handwritten)
# libraries have "release_blocked: true" so that releases are
# explicitly initiated
libraries:
  - id: "auth"
    release_blocked: true
  - id: "auth/oauth2adapt"
    release_blocked: true
  - id: "bigtable"
    release_blocked: true
  - id: "bigquery"
    release_blocked: true
  - id: "bigquery/v2"
    release_blocked: true
  - id: "compute/metadata"
    release_blocked: true
  - id: "datastore"
    release_blocked: true
  - id: "firestore"
    release_blocked: true
  - id: "pubsub"
    release_blocked: true
  - id: "pubsub/v2"
    release_blocked: true
  - id: "pubsublite"
    release_blocked: true
  - id: "root-module"
    release_blocked: true
  - id: "spanner"
    release_blocked: true
  - id: "storage"
    release_blocked: true
  - id: "vertexai"
    release_blocked: true
